### ISSUE TITLE
PHP 7 compatibility meta issue

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#16641]
- [x] Cannot use 'Null' as class name as it is reserved in /lib/private/memcache/null.php (https://github.com/owncloud/core/issues/16149 / done: https://github.com/owncloud/core/pull/16869)
- [x] php-parser uses String as class name (https://github.com/owncloud/core/issues/16640)
- [x] guzzlehttp - redefinition of parameter $ (https://github.com/owncloud/core/issues/16642)
- [x] PHP Fatal error: Uncaught EngineException: Class 'Imagick' not found on CI for PHP7 (https://github.com/owncloud/core/issues/17727)
- [x] Uncaught TypeException: Argument 3 passed to OC\Share\SearchResultSorter::__construct() must implement interface OCP\ILogger (https://github.com/owncloud/core/issues/16643)
- [x] mysql setup is failing because of #11788 
- [x] upgrade phpseclib - "PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Base has a deprecated constructor in /home/travis/build/owncloud/core/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 2009" (: https://github.com/owncloud/core/pull/18024)
- [x] Bump archive tar to upcoming 1.4.0  (https://github.com/owncloud/3rdparty/pull/191)
- [x] Change type hint to also accept Errors  (https://github.com/owncloud/core/pull/18050)
- [x] Update Pear to version not using class name as ctr
- [x] setting up on mysql seems to cause issues on jenkins and local ....
- [ ] OCI does not work (https://github.com/owncloud/core/issues/18425)
- …

**Comment by LukasReschke** [comment]
cc @DeepDiver1975 I took the freedom to create a meta issue for all PHP 7 issues. Couldn't find a lot of other show stoppers besides stuff like future deprecation notices…

```
1) Test_Archive_TAR::testGetFiles
Methods with the same name as their class will not be constructors in a future version of PHP; Archive_Tar has a deprecated constructor
```

etc.

**Comment by DeepDiver1975** [comment]
Nice - THX - looks like we need to come up with a PHP7 ci configuration ....

**Comment by DeepDiver1975** [comment]
Tata - https://ci.owncloud.org/job/server-master-linux-php7/1/

**Comment by LukasReschke** [comment]
```
Building remotely on vm-slave-02 (SLAVE docker) in workspace /var/jenkins/workspace/server-master-linux-php7/label/docker
[docker] $ /bin/sh -xe /tmp/hudson5931849964009290871.sh
+ docker run -d deepdiver/php7
Unable to find image 'deepdiver/php7' locally
Pulling repository deepdiver/php7
2015/06/01 01:04:52 Repository not found
+ DOCKER_CONTAINER_ID=
```

:see_no_evil:

**Comment by DeepDiver1975** [comment]
Take it easy - the image was not yet available last night ...

https://ci.owncloud.org/job/server-master-linux-php7/3/label=docker/console

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/sharepoint/pull/191#issuecomment-124441390

#11788 is now a 8.2 target because of PHP7

**Comment by LukasReschke** [comment]
@cweiske Any date for 1.4.0 as per https://github.com/pear/Archive_Tar/commit/b4b0d334c3a9c641634f8c2e6aa969f2d91b1f66? - We'd love to have ownCloud 8.2.0 compatible with PHP 7 :-)

**Comment by cweiske** [comment]
@LukasReschke: 1.4.0 is already out; it's now also tagged.

**Comment by LukasReschke** [comment]
Thanks @cweiske.

PHPSecLib: https://github.com/owncloud/core/pull/18024

**Comment by LukasReschke** [comment]
1 task remaining:  Update Pear to version not using class name as ctr

**Comment by LukasReschke** [comment]
Ref https://github.com/pear/pear-core/commit/4c2f834c7d28253a1d1df7464ae33919fbaba9e5, which is included in v1.10.0dev2 and v1.10.0dev1

**Comment by DeepDiver1975** [comment]
@cweiske any idea when pear-core will be released with the necessary fix? THX

**Comment by paulocoghi** [comment]
I'm anxious to see OC compatible with PHP7. If it already is 4x faster on the same PHP version, imagine with PHP 7.

**Comment by PVince81** [comment]
@LukasReschke only one checkbox left ? OCI ? :frowning: 

Move to 9.0 ?

**Comment by LukasReschke** [comment]
Pffft … ask @cmonteroluque or @MTRichards. https://github.com/owncloud/core/issues/18425 has more information. Besides this PHP 7 should work.

**Comment by MTRichards** [comment]
Does this mean that Oracle won't work with Doctrine on PHP 7? At least as an example of this.

**Comment by LukasReschke** [comment]
Correct. And the amount of people that use Oracle with PHP and Doctrine is rather low so it probably means that we have to fix it ourselves :tada: :birthday: :rocket: :dancers:

**Comment by MTRichards** [comment]
Ack! Ok, so we need to know this before PHP 7 comes out.
@bboule NOTE: Doctrine (and thus oC) won't work with Oracle and PHP 7. Just FYI for now...

**Comment by cmonteroluque** [comment]
I think this stays, at least for now

**Comment by MorrisJobke** [comment]
The only issue left is #18425 and is scheduled for 9.0

@DeepDiver1975 Can we close this ticket then?

**Comment by cweiske** [comment]
@DeepDiver1975: PEAR 1.10.0dev3 is out, which you can already use - it's most probably the version which will be released as 1.10.0 stable.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975: PEAR 1.10.0dev3 is out, which you can already use - it's most probably the version which will be released as 1.10.0 stable.

THX for the notification

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque I vote to close this with respect to the scope of 8.2 - we are in pretty good shape with 8.2 with respect to php7 - the oracle issue seems to be related to doctrine, which needs time for elaboration.

**Comment by karlitschek** [comment]
What does pretty good shape mean? :-)

**Comment by DeepDiver1975** [comment]
> What does pretty good shape mean? :-)

Unit tests on sqlite, mysql and pg are green for weeks: https://ci.owncloud.org/job/server-master-linux-php7/

**Comment by karlitschek** [comment]
so done? :-)

**Comment by DeepDiver1975** [comment]
> so done? :-)

with exception of Oracle - yes :tada:

**Comment by karlitschek** [comment]
sweet!
